# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 1016)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mplwindow = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setObjectName("mplwindow")
        self.mplvl = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvl.setObjectName("mplvl")
        self.horizontalLayout.addWidget(self.mplwindow)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.views = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.views.sizePolicy().hasHeightForWidth())
        self.views.setSizePolicy(sizePolicy)
        self.views.setMaximumSize(QtCore.QSize(200, 16777215))
        self.views.setObjectName("views")
        self.verticalLayout.addWidget(self.views)
        self.boxes = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxes.sizePolicy().hasHeightForWidth())
        self.boxes.setSizePolicy(sizePolicy)
        self.boxes.setMaximumSize(QtCore.QSize(200, 16777215))
        self.boxes.setObjectName("boxes")
        self.verticalLayout.addWidget(self.boxes)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuView_plot = QtWidgets.QMenu(self.menuView)
        self.menuView_plot.setObjectName("menuView_plot")
        self.menuSet_sensor = QtWidgets.QMenu(self.menubar)
        self.menuSet_sensor.setObjectName("menuSet_sensor")
        self.menuAnalyse_settings = QtWidgets.QMenu(self.menubar)
        self.menuAnalyse_settings.setObjectName("menuAnalyse_settings")
        self.menuSTART = QtWidgets.QMenu(self.menubar)
        self.menuSTART.setObjectName("menuSTART")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionConvert = QtWidgets.QAction(MainWindow)
        self.actionConvert.setObjectName("actionConvert")
        self.actionSubstract = QtWidgets.QAction(MainWindow)
        self.actionSubstract.setObjectName("actionSubstract")
        self.actionPixel_size = QtWidgets.QAction(MainWindow)
        self.actionPixel_size.setObjectName("actionPixel_size")
        self.actionMagnification = QtWidgets.QAction(MainWindow)
        self.actionMagnification.setObjectName("actionMagnification")
        self.actionSub_pixel_level = QtWidgets.QAction(MainWindow)
        self.actionSub_pixel_level.setObjectName("actionSub_pixel_level")
        self.actionEdit_objects_list = QtWidgets.QAction(MainWindow)
        self.actionEdit_objects_list.setObjectName("actionEdit_objects_list")
        self.actionViolin = QtWidgets.QAction(MainWindow)
        self.actionViolin.setCheckable(True)
        self.actionViolin.setChecked(True)
        self.actionViolin.setObjectName("actionViolin")
        self.actionPos = QtWidgets.QAction(MainWindow)
        self.actionPos.setCheckable(True)
        self.actionPos.setObjectName("actionPos")
        self.actionSub_frameset = QtWidgets.QAction(MainWindow)
        self.actionSub_frameset.setObjectName("actionSub_frameset")
        self.actionAdd_box = QtWidgets.QAction(MainWindow)
        self.actionAdd_box.setObjectName("actionAdd_box")
        self.actionStart_analysis = QtWidgets.QAction(MainWindow)
        self.actionStart_analysis.setObjectName("actionStart_analysis")
        self.actionx_shift = QtWidgets.QAction(MainWindow)
        self.actionx_shift.setCheckable(True)
        self.actionx_shift.setObjectName("actionx_shift")
        self.actiony_shift = QtWidgets.QAction(MainWindow)
        self.actiony_shift.setCheckable(True)
        self.actiony_shift.setObjectName("actiony_shift")
        self.actionShow_results = QtWidgets.QAction(MainWindow)
        self.actionShow_results.setObjectName("actionShow_results")
        self.actionExport_results = QtWidgets.QAction(MainWindow)
        self.actionExport_results.setObjectName("actionExport_results")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionConvert)
        self.menuFile.addAction(self.actionExport_results)
        self.menuView_plot.addAction(self.actionViolin)
        self.menuView_plot.addAction(self.actionPos)
        self.menuView_plot.addAction(self.actionx_shift)
        self.menuView_plot.addAction(self.actiony_shift)
        self.menuView.addAction(self.actionSubstract)
        self.menuView.addAction(self.menuView_plot.menuAction())
        self.menuView.addAction(self.actionSub_frameset)
        self.menuSet_sensor.addAction(self.actionPixel_size)
        self.menuSet_sensor.addAction(self.actionMagnification)
        self.menuAnalyse_settings.addAction(self.actionSub_pixel_level)
        self.menuAnalyse_settings.addAction(self.actionAdd_box)
        self.menuSTART.addAction(self.actionStart_analysis)
        self.menuSTART.addAction(self.actionShow_results)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSet_sensor.menuAction())
        self.menubar.addAction(self.menuAnalyse_settings.menuAction())
        self.menubar.addAction(self.menuSTART.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LPVM-NanoMotionAnalysis"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuView_plot.setTitle(_translate("MainWindow", "View plot"))
        self.menuSet_sensor.setTitle(_translate("MainWindow", "Set sensor"))
        self.menuAnalyse_settings.setTitle(_translate("MainWindow", "Analyse settings"))
        self.menuSTART.setTitle(_translate("MainWindow", "START"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open a file supported by PIMS (http://soft-matter.github.io/pims)"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionConvert.setText(_translate("MainWindow", "Convert"))
        self.actionConvert.setStatusTip(_translate("MainWindow", "Convert the previously opened file to .mp4 using ffmpeg"))
        self.actionSubstract.setText(_translate("MainWindow", "Substract"))
        self.actionSubstract.setStatusTip(_translate("MainWindow", "Substract the last frame from the 1st frame"))
        self.actionPixel_size.setText(_translate("MainWindow", "Pixel size"))
        self.actionMagnification.setText(_translate("MainWindow", "Magnification"))
        self.actionMagnification.setStatusTip(_translate("MainWindow", "Defines the optical zoom"))
        self.actionSub_pixel_level.setText(_translate("MainWindow", "Sub pixel level"))
        self.actionSub_pixel_level.setStatusTip(_translate("MainWindow", "100 is usually good"))
        self.actionEdit_objects_list.setText(_translate("MainWindow", "Edit objects list"))
        self.actionViolin.setText(_translate("MainWindow", "Violin"))
        self.actionPos.setText(_translate("MainWindow", "pos(t)"))
        self.actionSub_frameset.setText(_translate("MainWindow", "Sub-frameset"))
        self.actionSub_frameset.setStatusTip(_translate("MainWindow", "Select a set to show and analyse"))
        self.actionAdd_box.setText(_translate("MainWindow", "Add box"))
        self.actionAdd_box.setStatusTip(_translate("MainWindow", "Add zone to analyse. Modify it on screen"))
        self.actionAdd_box.setShortcut(_translate("MainWindow", "A"))
        self.actionStart_analysis.setText(_translate("MainWindow", "Start analysis"))
        self.actionStart_analysis.setShortcut(_translate("MainWindow", "S"))
        self.actionx_shift.setText(_translate("MainWindow", "x(t)_shift"))
        self.actiony_shift.setText(_translate("MainWindow", "y(t)_shift"))
        self.actionShow_results.setText(_translate("MainWindow", "Show results"))
        self.actionExport_results.setText(_translate("MainWindow", "Export results"))
